version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:860061945305:task-definition/authorization-service:1"
        LoadBalancerInfo:
          ContainerName: "authorization-service"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"